"""Consequence-matched phrase pairs, generated by the environments themselves.

The claim under test is *consequence-based geometry*: a representation shaped
by a predictor target should place two actions that have the SAME consequence
close together, and two actions with DIFFERENT consequences far apart, even
when the surface text says the opposite (a same-consequence pair can differ in
many tokens; a different-consequence pair can differ in one).

Every phrase here is produced by the environment's own renderer
(``igsm.render.action_phrase``, ``proofwriter.render_fact`` /
``RuleApplication.text``).  No new toy text is invented: only the arguments
handed to those renderers change.

Pair families
-------------
``paraphrase``   same consequence, different text.
    * stylized iGSM -- operand commutation for ``plus`` / ``times``:
      "derive X from A plus B" vs "derive X from B plus A".  Modular addition
      and multiplication commute, so X takes the identical value.
    * ProofWriter -- premise reordering inside one rule application: the
      premises are a set, so the derived fact is bit-identical.
``polarity``     different consequence, MINIMAL text change.
    * ProofWriter -- flipping one premise fact's polarity ("Anne is quiet."
      -> "Anne is not quiet."), a one-token edit that makes the rule
      inapplicable.  This is the genuine negation family.
    * stylized iGSM -- operator substitution ("plus" -> "times"), the closest
      available minimal-edit / maximal-consequence contrast in a domain with
      no negation.  Labelled ``operator_flip``, NOT called negation.
``control``      different consequence, comparable or larger text change
    (different operand, different target variable, a different legal rule
    application).

Each pair also carries the token-level edit distance between the two phrases,
so surface change can be regressed out of any distance claim.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field


# --------------------------------------------------------------------------- #
def token_edit_distance(a: str, b: str) -> int:
    """Levenshtein distance over whitespace tokens."""
    x, y = a.split(), b.split()
    prev = list(range(len(y) + 1))
    for i, xi in enumerate(x, 1):
        cur = [i]
        for j, yj in enumerate(y, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (xi != yj)))
        prev = cur
    return prev[-1]


@dataclass
class PairSpec:
    """One (base, alternative) phrase pair evaluated at one context."""

    family: str        # paraphrase | polarity | control
    subkind: str       # commuted_operands | premise_reorder | ...
    relation: str      # same_consequence | different_consequence
    base: str
    alt: str
    meta: dict = field(default_factory=dict)

    @property
    def edit_distance(self) -> int:
        return token_edit_distance(self.base, self.alt)

    def to_dict(self) -> dict:
        return {
            "family": self.family, "subkind": self.subkind,
            "relation": self.relation, "base": self.base, "alt": self.alt,
            "edit_distance": self.edit_distance, **self.meta,
        }


@dataclass
class ContextPairs:
    """All pairs sharing one causal history (encoded once)."""

    problem_id: str
    prompt: list[str]
    steps: list[str]
    pairs: list[PairSpec]

    @property
    def phrases(self) -> list[str]:
        seen: dict[str, int] = {}
        for p in self.pairs:
            for text in (p.base, p.alt):
                seen.setdefault(text, len(seen))
        return list(seen)

    def index_pairs(self) -> list[tuple[int, int, PairSpec]]:
        order = {t: i for i, t in enumerate(self.phrases)}
        return [(order[p.base], order[p.alt], p) for p in self.pairs]


# --------------------------------------------------------------------------- #
# stylized iGSM
# --------------------------------------------------------------------------- #
_COMMUTATIVE = {"add", "mul"}


def _styl_phrase(problem, target: int, a: int, b: int, op: str) -> str:
    """``action_phrase`` with explicit arguments (same template, same words)."""
    from textjepa.data.igsm.graph import OP_WORDS
    names = problem.vars
    return (
        f"derive {names[target].name} from {names[a].name} "
        f"{OP_WORDS[op]} {names[b].name} ."
    )


def _styl_value(problem, a: int, b: int, op: str) -> int:
    va, vb, m = problem.values[a], problem.values[b], problem.modulus
    return {"add": va + vb, "sub": va - vb, "mul": va * vb}[op] % m


def stylized_action_pairs(problem, trace, rng: random.Random,
                          max_per_problem: int = 3) -> list[PairSpec]:
    """Commutation paraphrases + operator/operand/target controls."""
    from textjepa.data.igsm.graph import OPS
    out: list[PairSpec] = []
    internal = [v for v in problem.vars if not v.is_leaf]
    rng.shuffle(internal)
    for v in internal:
        if len(out) >= 4 * max_per_problem:
            break
        a, b = v.parents
        if a == b:
            continue
        base = _styl_phrase(problem, v.idx, a, b, v.op)
        base_val = _styl_value(problem, a, b, v.op)
        # (1) paraphrase: commuted operands, only for commutative operators
        if v.op in _COMMUTATIVE:
            alt = _styl_phrase(problem, v.idx, b, a, v.op)
            if alt != base:
                out.append(PairSpec(
                    "paraphrase", "commuted_operands", "same_consequence",
                    base, alt,
                    {"target": v.idx, "op": v.op, "value": base_val},
                ))
        # (2) operator flip: one-token edit, different value
        others = [o for o in OPS if o != v.op
                  and _styl_value(problem, a, b, o) != base_val]
        if others:
            o = rng.choice(others)
            out.append(PairSpec(
                "polarity", "operator_flip", "different_consequence",
                base, _styl_phrase(problem, v.idx, a, b, o),
                {"target": v.idx, "op": v.op, "alt_op": o,
                 "value": base_val, "alt_value": _styl_value(problem, a, b, o)},
            ))
        # (3) operand substitution: same operator, different second operand
        cands = [c.idx for c in problem.vars
                 if c.idx not in (a, b, v.idx)
                 and _styl_value(problem, a, c.idx, v.op) != base_val]
        if cands:
            c = rng.choice(cands)
            out.append(PairSpec(
                "control", "different_operand", "different_consequence",
                base, _styl_phrase(problem, v.idx, a, c, v.op),
                {"target": v.idx, "op": v.op, "value": base_val,
                 "alt_value": _styl_value(problem, a, c, v.op)},
            ))
        # (4) target substitution: same operator and operands, other target
        tgts = [w.idx for w in problem.vars if w.idx != v.idx]
        if tgts:
            w = rng.choice(tgts)
            out.append(PairSpec(
                "control", "different_target", "different_consequence",
                base, _styl_phrase(problem, w, a, b, v.op),
                {"target": v.idx, "alt_target": w, "op": v.op},
            ))
    return out


def stylized_contexts(dataset, n: int, seed: int = 0,
                      max_per_problem: int = 3) -> list[ContextPairs]:
    from textjepa.data.igsm.render import prompt_sentences, step_sentence
    out = []
    for i in range(n):
        problem, prng = dataset.problem(i)
        rng = random.Random(f"pairs:{seed}:{i}")
        item = dataset[i]
        trace = list(item["var_idx"])
        prompt = prompt_sentences(problem, random.Random(f"prompt:{seed}:{i}"))
        t = rng.randrange(0, max(1, len(trace)))  # a real mid-trajectory state
        steps = [step_sentence(problem, trace[k]) for k in range(t)]
        pairs = stylized_action_pairs(problem, trace, rng, max_per_problem)
        if pairs:
            out.append(ContextPairs(f"styl-{i}", prompt, steps, pairs))
    return out


def stylized_state_commutation(dataset, n: int, seed: int = 0) -> list[dict]:
    """Order-invariance of STATES: two independent steps in either order.

    ``same`` : history + A + B   vs   history + B + A  (identical resolved set)
    ``diff`` : history + A + B   vs   history + A + C  (different resolved set)

    Nothing is invented -- both orders are legal trajectories the environment
    itself produces, rendered by ``step_sentence``.
    """
    from textjepa.data.igsm.env import SymbolicEnv
    from textjepa.data.igsm.render import prompt_sentences, step_sentence
    out = []
    for i in range(n):
        problem, _ = dataset.problem(i)
        rng = random.Random(f"commute:{seed}:{i}")
        prompt = prompt_sentences(problem, random.Random(f"prompt:{seed}:{i}"))
        env = SymbolicEnv(problem)
        prefix: list[str] = []
        for _ in range(rng.randrange(0, 3)):
            feas = env.feasible_actions()
            if not feas:
                break
            pick = rng.choice(feas)
            prefix.append(env.step(pick))
        feas = env.feasible_actions()
        if len(feas) < 3:
            continue
        a, b, c = rng.sample(feas, 3)
        def run(order):
            e = env.clone()
            return [e.step(x) for x in order]
        out.append({
            "problem_id": f"styl-{i}", "prompt": prompt, "prefix": prefix,
            "ab": run([a, b]), "ba": run([b, a]), "ac": run([a, c]),
        })
    return out


# --------------------------------------------------------------------------- #
# faithful iGSM
# --------------------------------------------------------------------------- #
FAITHFUL_ACTION_PARAPHRASE_NOTE = (
    "The faithful iGSM intent phrase is `Define <name> .` -- it names only the "
    "target parameter, with no operator and no operands. There is therefore NO "
    "natural same-consequence paraphrase of an action in this domain, and none "
    "is invented here. Consequence geometry on faithful is measured on the "
    "STATE side (order-invariance of two independent steps) instead."
)


def faithful_state_commutation(dataset, n: int, seed: int = 0) -> list[dict]:
    from textjepa.data.faithful import FaithfulEnv
    out = []
    for i in range(n):
        fp, _ = dataset.problem(i)
        rng = random.Random(f"commute:{seed}:{i}")
        env = FaithfulEnv(fp)
        prefix: list[str] = []
        for _ in range(rng.randrange(0, 3)):
            feas = env.feasible_actions()
            if not feas:
                break
            prefix.append(env.step(rng.choice(feas)))
        feas = env.feasible_actions()
        if len(feas) < 3:
            continue
        a, b, c = rng.sample(feas, 3)
        def run(order):
            e = env.clone()
            return [e.step(x) for x in order]
        out.append({
            "problem_id": f"faith-{i}", "prompt": list(fp.prompt_sentences),
            "prefix": prefix, "ab": run([a, b]), "ba": run([b, a]),
            "ac": run([a, c]),
        })
    return out


# --------------------------------------------------------------------------- #
# ProofWriter: the natural-negation domain
# --------------------------------------------------------------------------- #
def _flip(fact: tuple) -> tuple:
    return (*fact[:-1], "+" if fact[-1] == "-" else "-")


def proofwriter_contexts(episodes, n: int, seed: int = 0,
                         max_per_episode: int = 3) -> list[ContextPairs]:
    """Premise-reorder paraphrases and polarity-flip negations.

    The compiled episode carries ``metadata.environment_spec`` (initial facts +
    rules), so the fact state is replayed exactly and every phrase is rendered
    by ``RuleApplication.text`` / ``render_fact``.
    """
    from textjepa.data.proofwriter import (
        ProofRule, RuleApplication, rule_applications,
    )
    out: list[ContextPairs] = []
    for ep in episodes[:n]:
        spec = ep.metadata.get("environment_spec")
        if not spec:
            continue
        rng = random.Random(f"pw:{seed}:{ep.episode_id}")
        facts = frozenset(tuple(f) for f in spec["initial"])
        rules = tuple(
            ProofRule(r["rule_id"], r["text"],
                      tuple(tuple(a) for a in r["antecedents"]),
                      tuple(r["conclusion"]))
            for r in spec["rules"]
        )
        steps: list[str] = []
        for tr in ep.transitions:
            apps = rule_applications(facts, rules)
            by_text = {a.text: a for a in apps}
            app = by_text.get(tr.action)
            if app is None:
                break
            pairs: list[PairSpec] = []
            base = app.text
            # (1) paraphrase: premise order (premises are a set)
            if len(app.premises) >= 2 and len(set(app.premises)) >= 2:
                perm = list(app.premises)[::-1]
                alt = RuleApplication(app.rule, tuple(perm), app.conclusion).text
                if alt != base:
                    pairs.append(PairSpec(
                        "paraphrase", "premise_reorder", "same_consequence",
                        base, alt, {"conclusion": " ".join(app.conclusion)},
                    ))
            # (2) negation: flip one premise's polarity -> rule cannot fire
            for k in range(len(app.premises)):
                flipped = _flip(app.premises[k])
                if flipped in facts:
                    continue  # would still denote a known fact; skip
                prem = list(app.premises)
                prem[k] = flipped
                alt = RuleApplication(
                    app.rule, tuple(prem), app.conclusion
                ).text
                pairs.append(PairSpec(
                    "polarity", "premise_negation", "different_consequence",
                    base, alt,
                    {"conclusion": " ".join(app.conclusion),
                     "flipped_premise": " ".join(flipped)},
                ))
                break
            # (3) control: a different legal application at the same state
            others = [a for a in apps if a.text != base]
            if others:
                o = rng.choice(others)
                pairs.append(PairSpec(
                    "control", "other_legal_application",
                    "different_consequence", base, o.text,
                    {"conclusion": " ".join(app.conclusion),
                     "alt_conclusion": " ".join(o.conclusion)},
                ))
            if pairs:
                out.append(ContextPairs(
                    f"{ep.episode_id}@{len(steps)}", list(ep.prompt),
                    list(steps), pairs,
                ))
            facts = facts | {app.conclusion}
            steps.append(tr.outcome)
            if len([c for c in out if c.problem_id.startswith(ep.episode_id)]) \
                    >= max_per_episode:
                break
    return out
