from textjepa.objectives.base import Objective, CompositeObjective
from textjepa.objectives.prediction import (
    DenseHierarchyRolloutPrediction,
    DenseHierarchyValueRegression,
    DenseRolloutPrediction,
    HierarchyPrediction,
    HierarchyValueDistill,
    HierarchyValueRegression,
    LatentPrediction,
    MacroPrior,
    RolloutPrediction,
    TokenAlignedPrediction,
    TokenAlignedCounterfactualPrediction,
    TokenAlignedRolloutPrediction,
)
from textjepa.objectives.vicreg import SIGReg, VICReg
from textjepa.objectives.delta_action import DeltaAction, ObservedActionLDAD
from textjepa.objectives.value import (
    ActionDecode, ActionKL, GoalAdvantageDistill, ValueDistill, ValueRegression,
)
from textjepa.objectives.chunk_pred import ChunkPrediction, SlotAnchor
from textjepa.objectives.geometry import GoalMonotonicity, TemporalStraightening
from textjepa.objectives.ranking import ActionRanking, CostRanking, GeoAdvantageRank
from textjepa.objectives.counterfactual import (
    CounterfactualOutcomePrediction,
    CounterfactualSlotPrediction,
)
from textjepa.objectives.macro_hierarchy import (
    ActionFeasibility,
    HierarchyReachability,
    LowerHierarchyRollout,
    MacroActionValue,
    MacroAdvantageRanking,
    MacroOODValueRanking,
    MacroCounterfactualDynamics,
    MacroStateValue,
    MacroStateAdvantageRanking,
    MacroSupport,
    SubgoalActionRanking,
    MacroTop1Ranking,
    MacroRecedingRanking,
    MacroRecedingValue,
)
from textjepa.objectives.variational import (
    CounterfactualActionPrior,
    CounterfactualVariationalPrediction,
    LatentDifferenceActionReconstruction,
    TargetDistributionKL,
    VariationalLatentPrediction,
)
from textjepa.objectives.refinement import RefinementActionPrior

__all__ = [
    "ActionFeasibility",
    "HierarchyReachability",
    "LowerHierarchyRollout",
    "ActionRanking",
    "CostRanking",
    "GeoAdvantageRank",
    "CounterfactualOutcomePrediction",
    "CounterfactualSlotPrediction",
    "MacroCounterfactualDynamics",
    "MacroStateValue",
    "MacroStateAdvantageRanking",
    "MacroActionValue",
    "MacroAdvantageRanking",
    "MacroOODValueRanking",
    "MacroSupport",
    "SubgoalActionRanking",
    "MacroTop1Ranking",
    "MacroRecedingRanking",
    "MacroRecedingValue",
    "VariationalLatentPrediction",
    "TargetDistributionKL",
    "LatentDifferenceActionReconstruction",
    "CounterfactualVariationalPrediction",
    "CounterfactualActionPrior",
    "SIGReg",
    "ChunkPrediction",
    "SlotAnchor",
    "ValueDistill",
    "GoalAdvantageDistill",
    "ActionKL",
    "ActionDecode",
    "GoalMonotonicity",
    "TemporalStraightening",
    "Objective",
    "CompositeObjective",
    "LatentPrediction",
    "DenseRolloutPrediction",
    "DenseHierarchyRolloutPrediction",
    "DenseHierarchyValueRegression",
    "RolloutPrediction",
    "TokenAlignedPrediction",
    "TokenAlignedCounterfactualPrediction",
    "TokenAlignedRolloutPrediction",
    "HierarchyPrediction",
    "HierarchyValueDistill",
    "HierarchyValueRegression",
    "MacroPrior",
    "VICReg",
    "DeltaAction",
    "ObservedActionLDAD",
    "ValueRegression",
    "RefinementActionPrior",
]
