from textjepa.objectives.base import Objective, CompositeObjective
from textjepa.objectives.prediction import (
    DenseHierarchyRolloutPrediction,
    DenseHierarchyValueRegression,
    DenseRolloutPrediction,
    HierarchyPrediction,
    HierarchyValueDistill,
    HierarchyValueRegression,
    LatentPrediction,
    MacroPrior,
    MacroPriorDistillation,
    BaseActionValue,
    StateGoalDistance,
    MacroOptionReconstruction,
    MacroSentencePrediction,
    RolloutPrediction,
    TokenAlignedPrediction,
    TokenAlignedCounterfactualPrediction,
    TokenAlignedRolloutPrediction,
    SentenceLevelPrediction,
)
from textjepa.objectives.vicreg import MultiscaleVICReg, SIGReg, VICReg, VISReg
from textjepa.objectives.delta_action import (
    ActionGeneration,
    DeltaAction,
    ObservedActionLDAD,
    ObservedActionLDADCFContrast,
    ObservedActionLDADPredictorCycle,
)
from textjepa.objectives.energy_feasibility import EnergyCFFeasibilityRank
from textjepa.objectives.intent_prior import IntentPriorLM
from textjepa.objectives.value import (
    ActionDecode, ActionKL, GoalAdvantageDistill, ValueDistill, ValueRegression,
)
from textjepa.objectives.chunk_pred import ChunkPrediction, SlotAnchor
from textjepa.objectives.geometry import GoalMonotonicity, TemporalStraightening
from textjepa.objectives.ranking import (
    ActionRanking,
    CostRanking,
    GeoAdvantageRank,
    GeoAdvantageRegression,
    GeoEnergyRegression,
    GeoRolloutEnergyRegression,
    GeoRolloutAdvantageRank,
    GeoRolloutAdvantageRegression,
    GeoRolloutCandidateEnergyRegression,
    GeoHorizonRank,
    GeoHorizonEnergyRegression,
    GeoHorizonStraightening,
    GeoHorizonMonotonicity,
)
from textjepa.objectives.td_baselines import (
    ExpectileValueTD,
    GoalHeadDistill,
    TDJEPASuccessor,
    TDQ,
)
from textjepa.objectives.counterfactual import (
    CounterfactualOutcomePrediction,
    CounterfactualStatePrediction,
    CounterfactualSlotPrediction,
)
from textjepa.objectives.macro_hierarchy import (
    ActionFeasibility,
    GaussianActionPriorNLL,
    HierarchyReachability,
    LowerHierarchyRollout,
    MacroActionValue,
    MacroAdvantageRanking,
    MacroOODValueRanking,
    MacroCounterfactualDynamics,
    MacroStateValue,
    MacroStateAdvantageRanking,
    MacroSupport,
    SubgoalActionRanking,
    MacroTop1Ranking,
    MacroRecedingRanking,
    MacroRecedingValue,
)
from textjepa.objectives.variational import (
    CounterfactualActionPrior,
    CounterfactualVariationalPrediction,
    LatentDifferenceActionReconstruction,
    TargetDistributionKL,
    VariationalLatentPrediction,
)
from textjepa.objectives.refinement import RefinementActionPrior
from textjepa.objectives.hierarchical_language import (
    EMAShrunkMahalanobis,
    listwise_value_loss,
    terminal_set_discrepancy,
)

__all__ = [
    "ActionFeasibility",
    "EnergyCFFeasibilityRank",
    "IntentPriorLM",
    "ActionGeneration",
    "GaussianActionPriorNLL",
    "HierarchyReachability",
    "LowerHierarchyRollout",
    "ActionRanking",
    "CostRanking",
    "GeoAdvantageRank",
    "GeoAdvantageRegression",
    "GeoEnergyRegression",
    "GeoRolloutEnergyRegression",
    "GeoRolloutAdvantageRank",
    "GeoRolloutAdvantageRegression",
    "GeoRolloutCandidateEnergyRegression",
    "GeoHorizonRank",
    "GeoHorizonEnergyRegression",
    "GeoHorizonStraightening",
    "GeoHorizonMonotonicity",
    "TDQ",
    "ExpectileValueTD",
    "TDJEPASuccessor",
    "GoalHeadDistill",
    "CounterfactualOutcomePrediction",
    "CounterfactualStatePrediction",
    "CounterfactualSlotPrediction",
    "MacroCounterfactualDynamics",
    "MacroStateValue",
    "MacroStateAdvantageRanking",
    "MacroActionValue",
    "MacroAdvantageRanking",
    "MacroOODValueRanking",
    "MacroSupport",
    "SubgoalActionRanking",
    "MacroTop1Ranking",
    "MacroRecedingRanking",
    "MacroRecedingValue",
    "VariationalLatentPrediction",
    "TargetDistributionKL",
    "LatentDifferenceActionReconstruction",
    "CounterfactualVariationalPrediction",
    "CounterfactualActionPrior",
    "SIGReg",
    "VISReg",
    "ChunkPrediction",
    "SlotAnchor",
    "ValueDistill",
    "GoalAdvantageDistill",
    "ActionKL",
    "ActionDecode",
    "GoalMonotonicity",
    "TemporalStraightening",
    "Objective",
    "CompositeObjective",
    "LatentPrediction",
    "DenseRolloutPrediction",
    "DenseHierarchyRolloutPrediction",
    "DenseHierarchyValueRegression",
    "RolloutPrediction",
    "TokenAlignedPrediction",
    "TokenAlignedCounterfactualPrediction",
    "TokenAlignedRolloutPrediction",
    "HierarchyPrediction",
    "HierarchyValueDistill",
    "HierarchyValueRegression",
    "MacroPrior",
    "MacroPriorDistillation",
    "BaseActionValue",
    "StateGoalDistance",
    "MacroOptionReconstruction",
    "MacroSentencePrediction",
    "SentenceLevelPrediction",
    "VICReg",
    "MultiscaleVICReg",
    "DeltaAction",
    "ObservedActionLDAD",
    "ValueRegression",
    "RefinementActionPrior",
    "EMAShrunkMahalanobis",
    "listwise_value_loss",
    "terminal_set_discrepancy",
]
